### ISSUE TITLE
Query Entities to google and get the json from google

### ISSUE THREAD

**Issue by salvo4u** [salvo4u/seqouia2016#3]

**Comment by salvo4u** [comment]
- 
  [google_response.txt](https://github.com/salvo4u/seqouia2016/files/458920/google_response.txt)

**Comment by salvo4u** [comment]
I have attached the google json above that i got after pinging the Custom Search API from Google.
The search was for "chairs" on pepperfry.com and urbanladder.com

**Comment by amitanshg** [comment]
why are we pinging pepperfry/urbanladder, the idea is to directly return top-k results from google (in form of URLs). 

Eg. If I get an entity, "chair" and the serviceType: "Buy", I should ideally want to return buy chair links to the person on the other side of the chat. But, I worry that google search will reuturn HTML page and parsing it would be a problem. Any place where we can get a JSON file? or Convert the HTML to JSON?
